update utils script o last parseArger + fix esp32 unhappy casting

diff --git a/utils/buildFS b/utils/buildFS
--- a/utils/buildFS
+++ b/utils/buildFS
@@ -1,6 +1,7 @@
 #!/bin/bash
 # @parseArger-begin
-# @parseArger-help "I send an SOS to the world" --option "help" --short-option "h"
+# @parseArger-help "Build station filesystem" --option "help" --short-option "h"
+# @parseArger-verbose --option "verbose" --level "0"
 # @parseArger-declarations
 # @parseArger opt js "path to js file, ':' to separate target directory (/assets/js by default)" --short j --repeat
 # @parseArger opt css "path to css file, ':' to separate target directory (/assets/css by default)" --short c --repeat
@@ -8,18 +9,23 @@
 # @parseArger opt file "file to add, will be gzipped, ':' to separate target directory (/ by default)" --short f --repeat
 # @parseArger opt file-no-gz "add a file without gzip, ':' to separate target directory (/ by default)" --short F --repeat
 # @parseArger opt node "node executable" --default-value "node"
-# @parseArger opt pio "pio executable" --default-value "$HOME/.platformio/penv/bin/pio"
+# @parseArger opt pio "pio executable" --default-value "/home/didi/.platformio/penv/bin/pio"
 # @parseArger opt environement "build environment" --short e --default-value "nodemcuv2"
 # @parseArger opt upload "station to upload to, will set --environment" --short u
 # @parseArger flag dry "do not upload (just build for a station)" --short D
 # @parseArger-declarations-end
+
+# @parseArger-utils
+_helpHasBeenPrinted=1;
+_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)";
+# @parseArger-utils-end
 
 # @parseArger-parsing
 die()
 {
 	local _ret="${2:-1}"
 	test "${_PRINT_HELP:-no}" = yes && print_help >&2
-	echo "$1" >&2
+	log "$1" -3 >&2
 	exit "${_ret}"
 }
 
@@ -40,28 +46,67 @@ _arg_directory=()
 _arg_file=()
 _arg_file_no_gz=()
 _arg_node="node"
-_arg_pio="$HOME/.platformio/penv/bin/pio"
+_arg_pio="/home/didi/.platformio/penv/bin/pio"
 _arg_environement="nodemcuv2"
 _arg_upload=
 # FLAGS
 _arg_dry="off"
+_verbose_level="0";
+
 
 
 print_help()
 {
-	echo -e "I send an SOS to the world:"
+	_triggerSCHelp=1;
+
+	if [[ "$_helpHasBeenPrinted" == "1" ]]; then
+		_helpHasBeenPrinted=0;
+		echo -e "Build station filesystem:"
 	echo -e "	-j, --js <js>: path to js file, ':' to separate target directory (/assets/js by default), repeatable"
 	echo -e "	-c, --css <css>: path to css file, ':' to separate target directory (/assets/css by default), repeatable"
 	echo -e "	-d, --directory <directory>: additional directory path, all files will be gzipped, ':' to separate target directory (/ by default), repeatable"
 	echo -e "	-f, --file <file>: file to add, will be gzipped, ':' to separate target directory (/ by default), repeatable"
 	echo -e "	-F, --file-no-gz <file-no-gz>: add a file without gzip, ':' to separate target directory (/ by default), repeatable"
 	echo -e "	--node <node>: node executable [default: ' node ']"
-	echo -e "	--pio <pio>: pio executable [default: ' $HOME/.platformio/penv/bin/pio ']"
+	echo -e "	--pio <pio>: pio executable [default: ' /home/didi/.platformio/penv/bin/pio ']"
 	echo -e "	-e, --environement <environement>: build environment [default: ' nodemcuv2 ']"
 	echo -e "	-u, --upload <upload>: station to upload to, will set --environment"
 	echo -e "	-D|--dry|--no-dry: do not upload (just build for a station)"
 	echo -e "Usage :
-	$0 [--js <value>] [--css <value>] [--directory <value>] [--file <value>] [--file-no-gz <value>] [--node <value>] [--pio <value>] [--environement <value>] [--upload <value>] [--[no-]dry]"
+	$0 [--js <value>] [--css <value>] [--directory <value>] [--file <value>] [--file-no-gz <value>] [--node <value>] [--pio <value>] [--environement <value>] [--upload <value>] [--[no-]dry]";
+	fi
+
+}
+
+log() {
+	local _arg_msg="${1}";
+	local _arg_level="${2:"0"}";
+	if [ "${_arg_level}" -le "${_verbose_level}" ]; then
+		case "$_arg_level" in
+			-3)
+				_arg_COLOR="\033[0;31m";
+				;;
+			-2)
+				_arg_COLOR="\033[0;33m";
+				;;
+			-1)
+				_arg_COLOR="\033[1;33m";
+				;;
+			1)
+				_arg_COLOR="\033[0;32m";
+				;;
+			2)
+				_arg_COLOR="\033[1;36m";
+				;;
+			3)
+				_arg_COLOR="\033[0;36m";
+				;;
+			*)
+				_arg_COLOR="\033[0m";
+				;;
+		esac
+		echo -e "${_arg_COLOR}${_arg_msg}\033[0m";
+	fi
 }
 
 parse_commandline()
@@ -173,9 +218,11 @@ parse_commandline()
 				_arg_upload="${_key##-u}"
 				;;
 			
-			-D|--no-dry|--dry)
+			-D|--dry)
 				_arg_dry="on"
-				test "${1:0:5}" = "--no-" && _arg_dry="off"
+				;;
+			--no-dry)
+				_arg_dry="off"
 				;;
 			-h|--help)
 				print_help;
@@ -185,6 +232,23 @@ parse_commandline()
 				print_help;
 				exit 0;
 				;;
+			-v|--version)
+				print_version;
+				exit 0;
+				;;
+			-v*)
+				print_version;
+				exit 0;
+				;;
+			--verbose)
+				if [ $# -lt 2 ];then
+					_verbose_level="$((_verbose_level + 1))";
+				else
+					_verbose_level="$2";
+					shift;
+				fi
+				;;
+			
 			*)
 				_last_positional="$1"
 				_positionals+=("$_last_positional")
@@ -199,8 +263,13 @@ parse_commandline()
 handle_passed_args_count()
 {
 	local _required_args_string=""
-	test "${_positionals_count}" -le 0 || _PRINT_HELP=yes die "FATAL ERROR: There were spurious positional arguments --- we expect at most 0 (namely: $_required_args_string), but got ${_positionals_count} (the last one was: '${_last_positional}')." 1
-	test "${_positionals_count}" -ge 0 || _PRINT_HELP=yes die "FATAL ERROR: Not enough positional arguments - we require at least 0 (namely: $_required_args_string), but got only ${_positionals_count}." 1
+	if [ "${_positionals_count}" -gt 0 ] && [ "$_helpHasBeenPrinted" == "1" ];then
+		_PRINT_HELP=yes die "FATAL ERROR: There were spurious positional arguments --- we expect at most 0 (namely: $_required_args_string), but got ${_positionals_count} (the last one was: '${_last_positional}').\n\t${_positionals[*]}" 1
+	fi
+	if [ "${_positionals_count}" -lt 0 ] && [ "$_helpHasBeenPrinted" == "1" ];then
+		_PRINT_HELP=yes die "FATAL ERROR: Not enough positional arguments - we require at least 0 (namely: $_required_args_string), but got only ${_positionals_count}.
+	${_positionals[*]}" 1;
+	fi
 }
 
 
@@ -211,8 +280,8 @@ assign_positional_args()
 	shift "$_shift_for"
 	for _positional_name in ${_positional_names};do
 		test $# -gt 0 || break;
-		eval "if [ \"\$_one_of${_positional_name}\" != \"\" ];then [[ \"\${_one_of${_positional_name}[*]}\" =~ \"\${1}\" ]];fi" || die "${_positional_name} must be one of: $(eval "echo \"\${_one_of${_positional_name}[*]}\"")" 1
-eval "$_positional_name=\${1}" || die "Error during argument parsing, possibly an Argbash bug." 1;
+		eval "if [ \"\$_one_of${_positional_name}\" != \"\" ];then [[ \"\${_one_of${_positional_name}[*]}\" =~ \"\${1}\" ]];fi" || die "${_positional_name} must be one of: $(eval "echo \"\${_one_of${_positional_name}[*]}\"")" 1;
+		eval "$_positional_name=\${1}" || die "Error during argument parsing, possibly an ParseArger bug." 1;
 		shift;
 	done
 }
@@ -223,22 +292,34 @@ print_debug()
 	# shellcheck disable=SC2145
 	echo "DEBUG: $0 $@";
 	
-	echo -e "\tjs: ${_arg_js | sed 's/-/_/g'}";
-	echo -e "\tcss: ${_arg_css | sed 's/-/_/g'}";
-	echo -e "\tdirectory: ${_arg_directory | sed 's/-/_/g'}";
-	echo -e "\tfile: ${_arg_file | sed 's/-/_/g'}";
-	echo -e "\tfile-no-gz: ${_arg_file-no-gz | sed 's/-/_/g'}";
-	echo -e "\tnode: ${_arg_node | sed 's/-/_/g'}";
-	echo -e "\tpio: ${_arg_pio | sed 's/-/_/g'}";
-	echo -e "\tenvironement: ${_arg_environement | sed 's/-/_/g'}";
-	echo -e "\tupload: ${_arg_upload | sed 's/-/_/g'}";
-	echo -e "\tdry: ${_arg_dry | sed 's/-/_/g'}";
+	echo -e "\tjs: ${_arg_js[*]}";
+	echo -e "\tcss: ${_arg_css[*]}";
+	echo -e "\tdirectory: ${_arg_directory[*]}";
+	echo -e "\tfile: ${_arg_file[*]}";
+	echo -e "\tfile-no-gz: ${_arg_file_no_gz[*]}";
+	echo -e "\tnode: ${_arg_node}";
+	echo -e "\tpio: ${_arg_pio}";
+	echo -e "\tenvironement: ${_arg_environement}";
+	echo -e "\tupload: ${_arg_upload}";
+	echo -e "\tdry: ${_arg_dry}";
 
 }
 
-parse_commandline "$@"
-handle_passed_args_count
-assign_positional_args 1 "${_positionals[@]}"
+print_version()
+{
+	echo "";
+}
+
+on_interrupt() {
+	die Process aborted! 130;
+}
+
+parse_commandline "$@";
+handle_passed_args_count;
+assign_positional_args 1 "${_positionals[@]}";
+trap on_interrupt INT;
+
+
 
 # @parseArger-parsing-end
 # print_debug "$@"
diff --git a/utils/createStation b/utils/createStation
--- a/utils/createStation
+++ b/utils/createStation
@@ -1,6 +1,7 @@
 #!/bin/bash
 # @parseArger-begin
-# @parseArger-help "I send an SOS to the world" --option "help" --short-option "h"
+# @parseArger-help "Create a station" --option "help" --short-option "h"
+# @parseArger-verbose --option "verbose" --level "0"
 # @parseArger-declarations
 # @parseArger pos name "station name"
 # @parseArger opt ip "station ip"
@@ -9,12 +10,17 @@
 # @parseArger flag edit "open editor" --on
 # @parseArger-declarations-end
 
+# @parseArger-utils
+_helpHasBeenPrinted=1;
+_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)";
+# @parseArger-utils-end
+
 # @parseArger-parsing
 die()
 {
 	local _ret="${2:-1}"
 	test "${_PRINT_HELP:-no}" = yes && print_help >&2
-	echo "$1" >&2
+	log "$1" -3 >&2
 	exit "${_ret}"
 }
 
@@ -35,18 +41,57 @@ _arg_board=
 # FLAGS
 _arg_config="on"
 _arg_edit="on"
+_verbose_level="0";
+
 
 
 print_help()
 {
-	echo -e "I send an SOS to the world:"
+	_triggerSCHelp=1;
+
+	if [[ "$_helpHasBeenPrinted" == "1" ]]; then
+		_helpHasBeenPrinted=0;
+		echo -e "Create a station:"
 	echo -e "	name: station name"
 	echo -e "	--ip <ip>: station ip"
 	echo -e "	-b, --board <board>: PIO build environement name"
 	echo -e "	--config|--no-config: open configurator, on by default (use --no-config to turn it off)"
 	echo -e "	--edit|--no-edit: open editor, on by default (use --no-edit to turn it off)"
 	echo -e "Usage :
-	$0 <name> [--ip <value>] [--board <value>] [--[no-]config] [--[no-]edit]"
+	$0 <name> [--ip <value>] [--board <value>] [--[no-]config] [--[no-]edit]";
+	fi
+
+}
+
+log() {
+	local _arg_msg="${1}";
+	local _arg_level="${2:"0"}";
+	if [ "${_arg_level}" -le "${_verbose_level}" ]; then
+		case "$_arg_level" in
+			-3)
+				_arg_COLOR="\033[0;31m";
+				;;
+			-2)
+				_arg_COLOR="\033[0;33m";
+				;;
+			-1)
+				_arg_COLOR="\033[1;33m";
+				;;
+			1)
+				_arg_COLOR="\033[0;32m";
+				;;
+			2)
+				_arg_COLOR="\033[1;36m";
+				;;
+			3)
+				_arg_COLOR="\033[0;36m";
+				;;
+			*)
+				_arg_COLOR="\033[0m";
+				;;
+		esac
+		echo -e "${_arg_COLOR}${_arg_msg}\033[0m";
+	fi
 }
 
 parse_commandline()
@@ -77,13 +122,17 @@ parse_commandline()
 				_arg_board="${_key##-b}"
 				;;
 			
-			--no-config|--config)
+			--config)
 				_arg_config="on"
-				test "${1:0:5}" = "--no-" && _arg_config="off"
 				;;
-			--no-edit|--edit)
+			--no-config)
+				_arg_config="off"
+				;;
+			--edit)
 				_arg_edit="on"
-				test "${1:0:5}" = "--no-" && _arg_edit="off"
+				;;
+			--no-edit)
+				_arg_edit="off"
 				;;
 			-h|--help)
 				print_help;
@@ -93,6 +142,23 @@ parse_commandline()
 				print_help;
 				exit 0;
 				;;
+			-v|--version)
+				print_version;
+				exit 0;
+				;;
+			-v*)
+				print_version;
+				exit 0;
+				;;
+			--verbose)
+				if [ $# -lt 2 ];then
+					_verbose_level="$((_verbose_level + 1))";
+				else
+					_verbose_level="$2";
+					shift;
+				fi
+				;;
+			
 			*)
 				_last_positional="$1"
 				_positionals+=("$_last_positional")
@@ -107,8 +173,13 @@ parse_commandline()
 handle_passed_args_count()
 {
 	local _required_args_string="name"
-	test "${_positionals_count}" -le 1 || _PRINT_HELP=yes die "FATAL ERROR: There were spurious positional arguments --- we expect at most 1 (namely: $_required_args_string), but got ${_positionals_count} (the last one was: '${_last_positional}')." 1
-	test "${_positionals_count}" -ge 1 || _PRINT_HELP=yes die "FATAL ERROR: Not enough positional arguments - we require at least 1 (namely: $_required_args_string), but got only ${_positionals_count}." 1
+	if [ "${_positionals_count}" -gt 1 ] && [ "$_helpHasBeenPrinted" == "1" ];then
+		_PRINT_HELP=yes die "FATAL ERROR: There were spurious positional arguments --- we expect at most 1 (namely: $_required_args_string), but got ${_positionals_count} (the last one was: '${_last_positional}').\n\t${_positionals[*]}" 1
+	fi
+	if [ "${_positionals_count}" -lt 1 ] && [ "$_helpHasBeenPrinted" == "1" ];then
+		_PRINT_HELP=yes die "FATAL ERROR: Not enough positional arguments - we require at least 1 (namely: $_required_args_string), but got only ${_positionals_count}.
+	${_positionals[*]}" 1;
+	fi
 }
 
 
@@ -119,8 +190,8 @@ assign_positional_args()
 	shift "$_shift_for"
 	for _positional_name in ${_positional_names};do
 		test $# -gt 0 || break;
-		eval "if [ \"\$_one_of${_positional_name}\" != \"\" ];then [[ \"\${_one_of${_positional_name}[*]}\" =~ \"\${1}\" ]];fi" || die "${_positional_name} must be one of: $(eval "echo \"\${_one_of${_positional_name}[*]}\"")" 1
-eval "$_positional_name=\${1}" || die "Error during argument parsing, possibly an Argbash bug." 1;
+		eval "if [ \"\$_one_of${_positional_name}\" != \"\" ];then [[ \"\${_one_of${_positional_name}[*]}\" =~ \"\${1}\" ]];fi" || die "${_positional_name} must be one of: $(eval "echo \"\${_one_of${_positional_name}[*]}\"")" 1;
+		eval "$_positional_name=\${1}" || die "Error during argument parsing, possibly an ParseArger bug." 1;
 		shift;
 	done
 }
@@ -132,16 +203,28 @@ print_debug()
 	echo "DEBUG: $0 $@";
 	
 	echo -e "\tname: ${_arg_name}";
-	echo -e "\tip: ${_arg_ip | sed 's/-/_/g'}";
-	echo -e "\tboard: ${_arg_board | sed 's/-/_/g'}";
-	echo -e "\tconfig: ${_arg_config | sed 's/-/_/g'}";
-	echo -e "\tedit: ${_arg_edit | sed 's/-/_/g'}";
+	echo -e "\tip: ${_arg_ip}";
+	echo -e "\tboard: ${_arg_board}";
+	echo -e "\tconfig: ${_arg_config}";
+	echo -e "\tedit: ${_arg_edit}";
 
 }
 
-parse_commandline "$@"
-handle_passed_args_count
-assign_positional_args 1 "${_positionals[@]}"
+print_version()
+{
+	echo "";
+}
+
+on_interrupt() {
+	die Process aborted! 130;
+}
+
+parse_commandline "$@";
+handle_passed_args_count;
+assign_positional_args 1 "${_positionals[@]}";
+trap on_interrupt INT;
+
+
 
 # @parseArger-parsing-end
 # print_debug "$@"
diff --git a/utils/createStation-cli b/utils/createStation-cli
--- a/utils/createStation-cli
+++ b/utils/createStation-cli
@@ -1,6 +1,7 @@
 #!/bin/bash
 # @parseArger-begin
-# @parseArger-help "I send an SOS to the world" --option "help" --short-option "h"
+# @parseArger-help "[WIP] create a station main.cpp" --option "help" --short-option "h"
+# @parseArger-verbose --option "verbose" --level "0"
 # @parseArger-declarations
 # @parseArger pos name "station name"
 # @parseArger opt sensor "sensor to add" --short s --repeat
@@ -16,12 +17,17 @@
 # @parseArger opt file "file to output to"
 # @parseArger-declarations-end
 
+# @parseArger-utils
+_helpHasBeenPrinted=1;
+_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)";
+# @parseArger-utils-end
+
 # @parseArger-parsing
 die()
 {
 	local _ret="${2:-1}"
 	test "${_PRINT_HELP:-no}" = yes && print_help >&2
-	echo "$1" >&2
+	log "$1" -3 >&2
 	exit "${_ret}"
 }
 
@@ -49,11 +55,17 @@ _arg_loop=
 _arg_node="node"
 _arg_file=
 # FLAGS
+_verbose_level="0";
+
 
 
 print_help()
 {
-	echo -e "I send an SOS to the world:"
+	_triggerSCHelp=1;
+
+	if [[ "$_helpHasBeenPrinted" == "1" ]]; then
+		_helpHasBeenPrinted=0;
+		echo -e "[WIP] create a station main.cpp:"
 	echo -e "	name: station name"
 	echo -e "	-s, --sensor <sensor>: sensor to add, repeatable"
 	echo -e "	-t, --timer <timer>: timer to add, repeatable"
@@ -67,7 +79,40 @@ print_help()
 	echo -e "	--node <node>: node executable [default: ' node ']"
 	echo -e "	--file <file>: file to output to"
 	echo -e "Usage :
-	$0 <name> [--sensor <value>] [--timer <value>] [--endpoint <value>] [--wifi-ssid <value>] [--wifi-pass <value>] [--include <value>] [--declare <value>] [--setup <value>] [--loop <value>] [--node <value>] [--file <value>]"
+	$0 <name> [--sensor <value>] [--timer <value>] [--endpoint <value>] [--wifi-ssid <value>] [--wifi-pass <value>] [--include <value>] [--declare <value>] [--setup <value>] [--loop <value>] [--node <value>] [--file <value>]";
+	fi
+
+}
+
+log() {
+	local _arg_msg="${1}";
+	local _arg_level="${2:"0"}";
+	if [ "${_arg_level}" -le "${_verbose_level}" ]; then
+		case "$_arg_level" in
+			-3)
+				_arg_COLOR="\033[0;31m";
+				;;
+			-2)
+				_arg_COLOR="\033[0;33m";
+				;;
+			-1)
+				_arg_COLOR="\033[1;33m";
+				;;
+			1)
+				_arg_COLOR="\033[0;32m";
+				;;
+			2)
+				_arg_COLOR="\033[1;36m";
+				;;
+			3)
+				_arg_COLOR="\033[0;36m";
+				;;
+			*)
+				_arg_COLOR="\033[0m";
+				;;
+		esac
+		echo -e "${_arg_COLOR}${_arg_msg}\033[0m";
+	fi
 }
 
 parse_commandline()
@@ -199,6 +244,23 @@ parse_commandline()
 				print_help;
 				exit 0;
 				;;
+			-v|--version)
+				print_version;
+				exit 0;
+				;;
+			-v*)
+				print_version;
+				exit 0;
+				;;
+			--verbose)
+				if [ $# -lt 2 ];then
+					_verbose_level="$((_verbose_level + 1))";
+				else
+					_verbose_level="$2";
+					shift;
+				fi
+				;;
+			
 			*)
 				_last_positional="$1"
 				_positionals+=("$_last_positional")
@@ -213,8 +275,13 @@ parse_commandline()
 handle_passed_args_count()
 {
 	local _required_args_string="name"
-	test "${_positionals_count}" -le 1 || _PRINT_HELP=yes die "FATAL ERROR: There were spurious positional arguments --- we expect at most 1 (namely: $_required_args_string), but got ${_positionals_count} (the last one was: '${_last_positional}')." 1
-	test "${_positionals_count}" -ge 1 || _PRINT_HELP=yes die "FATAL ERROR: Not enough positional arguments - we require at least 1 (namely: $_required_args_string), but got only ${_positionals_count}." 1
+	if [ "${_positionals_count}" -gt 1 ] && [ "$_helpHasBeenPrinted" == "1" ];then
+		_PRINT_HELP=yes die "FATAL ERROR: There were spurious positional arguments --- we expect at most 1 (namely: $_required_args_string), but got ${_positionals_count} (the last one was: '${_last_positional}').\n\t${_positionals[*]}" 1
+	fi
+	if [ "${_positionals_count}" -lt 1 ] && [ "$_helpHasBeenPrinted" == "1" ];then
+		_PRINT_HELP=yes die "FATAL ERROR: Not enough positional arguments - we require at least 1 (namely: $_required_args_string), but got only ${_positionals_count}.
+	${_positionals[*]}" 1;
+	fi
 }
 
 
@@ -225,8 +292,8 @@ assign_positional_args()
 	shift "$_shift_for"
 	for _positional_name in ${_positional_names};do
 		test $# -gt 0 || break;
-		eval "if [ \"\$_one_of${_positional_name}\" != \"\" ];then [[ \"\${_one_of${_positional_name}[*]}\" =~ \"\${1}\" ]];fi" || die "${_positional_name} must be one of: $(eval "echo \"\${_one_of${_positional_name}[*]}\"")" 1
-eval "$_positional_name=\${1}" || die "Error during argument parsing, possibly an Argbash bug." 1;
+		eval "if [ \"\$_one_of${_positional_name}\" != \"\" ];then [[ \"\${_one_of${_positional_name}[*]}\" =~ \"\${1}\" ]];fi" || die "${_positional_name} must be one of: $(eval "echo \"\${_one_of${_positional_name}[*]}\"")" 1;
+		eval "$_positional_name=\${1}" || die "Error during argument parsing, possibly an ParseArger bug." 1;
 		shift;
 	done
 }
@@ -238,23 +305,35 @@ print_debug()
 	echo "DEBUG: $0 $@";
 	
 	echo -e "\tname: ${_arg_name}";
-	echo -e "\tsensor: ${_arg_sensor | sed 's/-/_/g'}";
-	echo -e "\ttimer: ${_arg_timer | sed 's/-/_/g'}";
-	echo -e "\tendpoint: ${_arg_endpoint | sed 's/-/_/g'}";
-	echo -e "\twifi-ssid: ${_arg_wifi-ssid | sed 's/-/_/g'}";
-	echo -e "\twifi-pass: ${_arg_wifi-pass | sed 's/-/_/g'}";
-	echo -e "\tinclude: ${_arg_include | sed 's/-/_/g'}";
-	echo -e "\tdeclare: ${_arg_declare | sed 's/-/_/g'}";
-	echo -e "\tsetup: ${_arg_setup | sed 's/-/_/g'}";
-	echo -e "\tloop: ${_arg_loop | sed 's/-/_/g'}";
-	echo -e "\tnode: ${_arg_node | sed 's/-/_/g'}";
-	echo -e "\tfile: ${_arg_file | sed 's/-/_/g'}";
+	echo -e "\tsensor: ${_arg_sensor[*]}";
+	echo -e "\ttimer: ${_arg_timer[*]}";
+	echo -e "\tendpoint: ${_arg_endpoint[*]}";
+	echo -e "\twifi-ssid: ${_arg_wifi_ssid}";
+	echo -e "\twifi-pass: ${_arg_wifi_pass}";
+	echo -e "\tinclude: ${_arg_include}";
+	echo -e "\tdeclare: ${_arg_declare}";
+	echo -e "\tsetup: ${_arg_setup}";
+	echo -e "\tloop: ${_arg_loop}";
+	echo -e "\tnode: ${_arg_node}";
+	echo -e "\tfile: ${_arg_file}";
 
 }
 
-parse_commandline "$@"
-handle_passed_args_count
-assign_positional_args 1 "${_positionals[@]}"
+print_version()
+{
+	echo "";
+}
+
+on_interrupt() {
+	die Process aborted! 130;
+}
+
+parse_commandline "$@";
+handle_passed_args_count;
+assign_positional_args 1 "${_positionals[@]}";
+trap on_interrupt INT;
+
+
 
 # @parseArger-parsing-end
 # print_debug "$@"
diff --git a/utils/setStation b/utils/setStation
--- a/utils/setStation
+++ b/utils/setStation
@@ -1,23 +1,29 @@
 #!/bin/bash
 # @parseArger-begin
-# @parseArger-help "I send an SOS to the world" --option "help" --short-option "h"
+# @parseArger-help "Set station configuration" --option "help" --short-option "h"
+# @parseArger-verbose --option "verbose" --level "0"
 # @parseArger-declarations
 # @parseArger pos name "station name"
 # @parseArger opt sensor "sensor to add" --short s --repeat
 # @parseArger opt ip "ip address" --short i --default-value "0"
-# @parseArger opt board "pio env" --default-value "nodemcuv2"
-# @parseArger opt data-file "data-file to add" --repeat
-# @parseArger opt data-directory "data-directory to add" --repeat
-# @parseArger opt js "js to add" --repeat
-# @parseArger opt css "css to add" --repeat
+# @parseArger opt board "pio env" --short b --default-value "nodemcuv2"
+# @parseArger opt data-file "data-file to add" --short f --repeat
+# @parseArger opt data-directory "data-directory to add" --short d --repeat
+# @parseArger opt js "js to add" --short j --repeat
+# @parseArger opt css "css to add" --short c --repeat
 # @parseArger-declarations-end
+
+# @parseArger-utils
+_helpHasBeenPrinted=1;
+_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)";
+# @parseArger-utils-end
 
 # @parseArger-parsing
 die()
 {
 	local _ret="${2:-1}"
 	test "${_PRINT_HELP:-no}" = yes && print_help >&2
-	echo "$1" >&2
+	log "$1" -3 >&2
 	exit "${_ret}"
 }
 
@@ -41,21 +47,60 @@ _arg_data_directory=()
 _arg_js=()
 _arg_css=()
 # FLAGS
+_verbose_level="0";
+
 
 
 print_help()
 {
-	echo -e "I send an SOS to the world:"
+	_triggerSCHelp=1;
+
+	if [[ "$_helpHasBeenPrinted" == "1" ]]; then
+		_helpHasBeenPrinted=0;
+		echo -e "Set station configuration:"
 	echo -e "	name: station name"
 	echo -e "	-s, --sensor <sensor>: sensor to add, repeatable"
 	echo -e "	-i, --ip <ip>: ip address [default: ' 0 ']"
-	echo -e "	--board <board>: pio env [default: ' nodemcuv2 ']"
-	echo -e "	--data-file <data-file>: data-file to add, repeatable"
-	echo -e "	--data-directory <data-directory>: data-directory to add, repeatable"
-	echo -e "	--js <js>: js to add, repeatable"
-	echo -e "	--css <css>: css to add, repeatable"
+	echo -e "	-b, --board <board>: pio env [default: ' nodemcuv2 ']"
+	echo -e "	-f, --data-file <data-file>: data-file to add, repeatable"
+	echo -e "	-d, --data-directory <data-directory>: data-directory to add, repeatable"
+	echo -e "	-j, --js <js>: js to add, repeatable"
+	echo -e "	-c, --css <css>: css to add, repeatable"
 	echo -e "Usage :
-	$0 <name> [--sensor <value>] [--ip <value>] [--board <value>] [--data-file <value>] [--data-directory <value>] [--js <value>] [--css <value>]"
+	$0 <name> [--sensor <value>] [--ip <value>] [--board <value>] [--data-file <value>] [--data-directory <value>] [--js <value>] [--css <value>]";
+	fi
+
+}
+
+log() {
+	local _arg_msg="${1}";
+	local _arg_level="${2:"0"}";
+	if [ "${_arg_level}" -le "${_verbose_level}" ]; then
+		case "$_arg_level" in
+			-3)
+				_arg_COLOR="\033[0;31m";
+				;;
+			-2)
+				_arg_COLOR="\033[0;33m";
+				;;
+			-1)
+				_arg_COLOR="\033[1;33m";
+				;;
+			1)
+				_arg_COLOR="\033[0;32m";
+				;;
+			2)
+				_arg_COLOR="\033[1;36m";
+				;;
+			3)
+				_arg_COLOR="\033[0;36m";
+				;;
+			*)
+				_arg_COLOR="\033[0m";
+				;;
+		esac
+		echo -e "${_arg_COLOR}${_arg_msg}\033[0m";
+	fi
 }
 
 parse_commandline()
@@ -89,7 +134,7 @@ parse_commandline()
 				_arg_ip="${_key##-i}"
 				;;
 			
-			--board)
+			-b|--board)
 				test $# -lt 2 && die "Missing value for the option: '$_key'" 1
 				_arg_board="$2"
 				shift
@@ -97,8 +142,11 @@ parse_commandline()
 			--board=*)
 				_arg_board="${_key##--board=}"
 				;;
+			-b*)
+				_arg_board="${_key##-b}"
+				;;
 			
-			--data-file)
+			-f|--data-file)
 				test $# -lt 2 && die "Missing value for the option: '$_key'" 1
 				_arg_data_file+=("$2")
 				shift
@@ -106,8 +154,11 @@ parse_commandline()
 			--data-file=*)
 				_arg_data_file+=("${_key##--data-file=}")
 				;;
+			-f*)
+				_arg_data_file+=("${_key##-f}")
+				;;
 			
-			--data-directory)
+			-d|--data-directory)
 				test $# -lt 2 && die "Missing value for the option: '$_key'" 1
 				_arg_data_directory+=("$2")
 				shift
@@ -115,8 +166,11 @@ parse_commandline()
 			--data-directory=*)
 				_arg_data_directory+=("${_key##--data-directory=}")
 				;;
+			-d*)
+				_arg_data_directory+=("${_key##-d}")
+				;;
 			
-			--js)
+			-j|--js)
 				test $# -lt 2 && die "Missing value for the option: '$_key'" 1
 				_arg_js+=("$2")
 				shift
@@ -124,14 +178,20 @@ parse_commandline()
 			--js=*)
 				_arg_js+=("${_key##--js=}")
 				;;
+			-j*)
+				_arg_js+=("${_key##-j}")
+				;;
 			
-			--css)
+			-c|--css)
 				test $# -lt 2 && die "Missing value for the option: '$_key'" 1
 				_arg_css+=("$2")
 				shift
 				;;
 			--css=*)
 				_arg_css+=("${_key##--css=}")
+				;;
+			-c*)
+				_arg_css+=("${_key##-c}")
 				;;
 			
 			-h|--help)
@@ -142,6 +202,23 @@ parse_commandline()
 				print_help;
 				exit 0;
 				;;
+			-v|--version)
+				print_version;
+				exit 0;
+				;;
+			-v*)
+				print_version;
+				exit 0;
+				;;
+			--verbose)
+				if [ $# -lt 2 ];then
+					_verbose_level="$((_verbose_level + 1))";
+				else
+					_verbose_level="$2";
+					shift;
+				fi
+				;;
+			
 			*)
 				_last_positional="$1"
 				_positionals+=("$_last_positional")
@@ -156,8 +233,13 @@ parse_commandline()
 handle_passed_args_count()
 {
 	local _required_args_string="name"
-	test "${_positionals_count}" -le 1 || _PRINT_HELP=yes die "FATAL ERROR: There were spurious positional arguments --- we expect at most 1 (namely: $_required_args_string), but got ${_positionals_count} (the last one was: '${_last_positional}')." 1
-	test "${_positionals_count}" -ge 1 || _PRINT_HELP=yes die "FATAL ERROR: Not enough positional arguments - we require at least 1 (namely: $_required_args_string), but got only ${_positionals_count}." 1
+	if [ "${_positionals_count}" -gt 1 ] && [ "$_helpHasBeenPrinted" == "1" ];then
+		_PRINT_HELP=yes die "FATAL ERROR: There were spurious positional arguments --- we expect at most 1 (namely: $_required_args_string), but got ${_positionals_count} (the last one was: '${_last_positional}').\n\t${_positionals[*]}" 1
+	fi
+	if [ "${_positionals_count}" -lt 1 ] && [ "$_helpHasBeenPrinted" == "1" ];then
+		_PRINT_HELP=yes die "FATAL ERROR: Not enough positional arguments - we require at least 1 (namely: $_required_args_string), but got only ${_positionals_count}.
+	${_positionals[*]}" 1;
+	fi
 }
 
 
@@ -168,8 +250,8 @@ assign_positional_args()
 	shift "$_shift_for"
 	for _positional_name in ${_positional_names};do
 		test $# -gt 0 || break;
-		eval "if [ \"\$_one_of${_positional_name}\" != \"\" ];then [[ \"\${_one_of${_positional_name}[*]}\" =~ \"\${1}\" ]];fi" || die "${_positional_name} must be one of: $(eval "echo \"\${_one_of${_positional_name}[*]}\"")" 1
-eval "$_positional_name=\${1}" || die "Error during argument parsing, possibly an Argbash bug." 1;
+		eval "if [ \"\$_one_of${_positional_name}\" != \"\" ];then [[ \"\${_one_of${_positional_name}[*]}\" =~ \"\${1}\" ]];fi" || die "${_positional_name} must be one of: $(eval "echo \"\${_one_of${_positional_name}[*]}\"")" 1;
+		eval "$_positional_name=\${1}" || die "Error during argument parsing, possibly an ParseArger bug." 1;
 		shift;
 	done
 }
@@ -181,19 +263,31 @@ print_debug()
 	echo "DEBUG: $0 $@";
 	
 	echo -e "\tname: ${_arg_name}";
-	echo -e "\tsensor: ${_arg_sensor | sed 's/-/_/g'}";
-	echo -e "\tip: ${_arg_ip | sed 's/-/_/g'}";
-	echo -e "\tboard: ${_arg_board | sed 's/-/_/g'}";
-	echo -e "\tdata-file: ${_arg_data-file | sed 's/-/_/g'}";
-	echo -e "\tdata-directory: ${_arg_data-directory | sed 's/-/_/g'}";
-	echo -e "\tjs: ${_arg_js | sed 's/-/_/g'}";
-	echo -e "\tcss: ${_arg_css | sed 's/-/_/g'}";
+	echo -e "\tsensor: ${_arg_sensor[*]}";
+	echo -e "\tip: ${_arg_ip}";
+	echo -e "\tboard: ${_arg_board}";
+	echo -e "\tdata-file: ${_arg_data_file[*]}";
+	echo -e "\tdata-directory: ${_arg_data_directory[*]}";
+	echo -e "\tjs: ${_arg_js[*]}";
+	echo -e "\tcss: ${_arg_css[*]}";
 
 }
 
-parse_commandline "$@"
-handle_passed_args_count
-assign_positional_args 1 "${_positionals[@]}"
+print_version()
+{
+	echo "";
+}
+
+on_interrupt() {
+	die Process aborted! 130;
+}
+
+parse_commandline "$@";
+handle_passed_args_count;
+assign_positional_args 1 "${_positionals[@]}";
+trap on_interrupt INT;
+
+
 
 # @parseArger-parsing-end
 # print_debug "$@"
diff --git a/utils/uploadStation b/utils/uploadStation
--- a/utils/uploadStation
+++ b/utils/uploadStation
@@ -1,22 +1,28 @@
 #!/bin/bash
 # @parseArger-begin
-# @parseArger-help "I send an SOS to the world" --option "help" --short-option "h"
+# @parseArger-help "Upload a station to the board" --option "help" --short-option "h"
+# @parseArger-verbose --option "verbose" --level "0"
 # @parseArger-declarations
 # @parseArger pos name "station name"
 # @parseArger opt ip "station ip"
-# @parseArger opt port "host port upload flags, avoid random for firewalls" --default-value "46667"
+# @parseArger opt port "host port upload flags, avoid random for firewalls" --short p --default-value "46667"
 # @parseArger opt board "PIO build environement name" --short b
-# @parseArger opt pio "pio executable" --default-value "$HOME/.platformio/penv/bin/pio"
+# @parseArger opt pio "pio executable" --default-value "/home/didi/.platformio/penv/bin/pio"
 # @parseArger flag ota "OTA update" --on
 # @parseArger flag fs "upload fs"
 # @parseArger-declarations-end
+
+# @parseArger-utils
+_helpHasBeenPrinted=1;
+_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)";
+# @parseArger-utils-end
 
 # @parseArger-parsing
 die()
 {
 	local _ret="${2:-1}"
 	test "${_PRINT_HELP:-no}" = yes && print_help >&2
-	echo "$1" >&2
+	log "$1" -3 >&2
 	exit "${_ret}"
 }
 
@@ -35,24 +41,63 @@ _arg_name="";
 _arg_ip=
 _arg_port="46667"
 _arg_board=
-_arg_pio="$HOME/.platformio/penv/bin/pio"
+_arg_pio="/home/didi/.platformio/penv/bin/pio"
 # FLAGS
 _arg_ota="on"
 _arg_fs="off"
+_verbose_level="0";
+
 
 
 print_help()
 {
-	echo -e "I send an SOS to the world:"
+	_triggerSCHelp=1;
+
+	if [[ "$_helpHasBeenPrinted" == "1" ]]; then
+		_helpHasBeenPrinted=0;
+		echo -e "Upload a station to the board:"
 	echo -e "	name: station name"
 	echo -e "	--ip <ip>: station ip"
-	echo -e "	--port <port>: host port upload flags, avoid random for firewalls [default: ' 46667 ']"
+	echo -e "	-p, --port <port>: host port upload flags, avoid random for firewalls [default: ' 46667 ']"
 	echo -e "	-b, --board <board>: PIO build environement name"
-	echo -e "	--pio <pio>: pio executable [default: ' $HOME/.platformio/penv/bin/pio ']"
+	echo -e "	--pio <pio>: pio executable [default: ' /home/didi/.platformio/penv/bin/pio ']"
 	echo -e "	--ota|--no-ota: OTA update, on by default (use --no-ota to turn it off)"
 	echo -e "	--fs|--no-fs: upload fs"
 	echo -e "Usage :
-	$0 <name> [--ip <value>] [--port <value>] [--board <value>] [--pio <value>] [--[no-]ota] [--[no-]fs]"
+	$0 <name> [--ip <value>] [--port <value>] [--board <value>] [--pio <value>] [--[no-]ota] [--[no-]fs]";
+	fi
+
+}
+
+log() {
+	local _arg_msg="${1}";
+	local _arg_level="${2:"0"}";
+	if [ "${_arg_level}" -le "${_verbose_level}" ]; then
+		case "$_arg_level" in
+			-3)
+				_arg_COLOR="\033[0;31m";
+				;;
+			-2)
+				_arg_COLOR="\033[0;33m";
+				;;
+			-1)
+				_arg_COLOR="\033[1;33m";
+				;;
+			1)
+				_arg_COLOR="\033[0;32m";
+				;;
+			2)
+				_arg_COLOR="\033[1;36m";
+				;;
+			3)
+				_arg_COLOR="\033[0;36m";
+				;;
+			*)
+				_arg_COLOR="\033[0m";
+				;;
+		esac
+		echo -e "${_arg_COLOR}${_arg_msg}\033[0m";
+	fi
 }
 
 parse_commandline()
@@ -71,13 +116,16 @@ parse_commandline()
 				_arg_ip="${_key##--ip=}"
 				;;
 			
-			--port)
+			-p|--port)
 				test $# -lt 2 && die "Missing value for the option: '$_key'" 1
 				_arg_port="$2"
 				shift
 				;;
 			--port=*)
 				_arg_port="${_key##--port=}"
+				;;
+			-p*)
+				_arg_port="${_key##-p}"
 				;;
 			
 			-b|--board)
@@ -101,13 +149,17 @@ parse_commandline()
 				_arg_pio="${_key##--pio=}"
 				;;
 			
-			--no-ota|--ota)
+			--ota)
 				_arg_ota="on"
-				test "${1:0:5}" = "--no-" && _arg_ota="off"
 				;;
-			--no-fs|--fs)
+			--no-ota)
+				_arg_ota="off"
+				;;
+			--fs)
 				_arg_fs="on"
-				test "${1:0:5}" = "--no-" && _arg_fs="off"
+				;;
+			--no-fs)
+				_arg_fs="off"
 				;;
 			-h|--help)
 				print_help;
@@ -117,6 +169,23 @@ parse_commandline()
 				print_help;
 				exit 0;
 				;;
+			-v|--version)
+				print_version;
+				exit 0;
+				;;
+			-v*)
+				print_version;
+				exit 0;
+				;;
+			--verbose)
+				if [ $# -lt 2 ];then
+					_verbose_level="$((_verbose_level + 1))";
+				else
+					_verbose_level="$2";
+					shift;
+				fi
+				;;
+			
 			*)
 				_last_positional="$1"
 				_positionals+=("$_last_positional")
@@ -131,8 +200,13 @@ parse_commandline()
 handle_passed_args_count()
 {
 	local _required_args_string="name"
-	test "${_positionals_count}" -le 1 || _PRINT_HELP=yes die "FATAL ERROR: There were spurious positional arguments --- we expect at most 1 (namely: $_required_args_string), but got ${_positionals_count} (the last one was: '${_last_positional}')." 1
-	test "${_positionals_count}" -ge 1 || _PRINT_HELP=yes die "FATAL ERROR: Not enough positional arguments - we require at least 1 (namely: $_required_args_string), but got only ${_positionals_count}." 1
+	if [ "${_positionals_count}" -gt 1 ] && [ "$_helpHasBeenPrinted" == "1" ];then
+		_PRINT_HELP=yes die "FATAL ERROR: There were spurious positional arguments --- we expect at most 1 (namely: $_required_args_string), but got ${_positionals_count} (the last one was: '${_last_positional}').\n\t${_positionals[*]}" 1
+	fi
+	if [ "${_positionals_count}" -lt 1 ] && [ "$_helpHasBeenPrinted" == "1" ];then
+		_PRINT_HELP=yes die "FATAL ERROR: Not enough positional arguments - we require at least 1 (namely: $_required_args_string), but got only ${_positionals_count}.
+	${_positionals[*]}" 1;
+	fi
 }
 
 
@@ -143,8 +217,8 @@ assign_positional_args()
 	shift "$_shift_for"
 	for _positional_name in ${_positional_names};do
 		test $# -gt 0 || break;
-		eval "if [ \"\$_one_of${_positional_name}\" != \"\" ];then [[ \"\${_one_of${_positional_name}[*]}\" =~ \"\${1}\" ]];fi" || die "${_positional_name} must be one of: $(eval "echo \"\${_one_of${_positional_name}[*]}\"")" 1
-eval "$_positional_name=\${1}" || die "Error during argument parsing, possibly an Argbash bug." 1;
+		eval "if [ \"\$_one_of${_positional_name}\" != \"\" ];then [[ \"\${_one_of${_positional_name}[*]}\" =~ \"\${1}\" ]];fi" || die "${_positional_name} must be one of: $(eval "echo \"\${_one_of${_positional_name}[*]}\"")" 1;
+		eval "$_positional_name=\${1}" || die "Error during argument parsing, possibly an ParseArger bug." 1;
 		shift;
 	done
 }
@@ -156,18 +230,30 @@ print_debug()
 	echo "DEBUG: $0 $@";
 	
 	echo -e "\tname: ${_arg_name}";
-	echo -e "\tip: ${_arg_ip | sed 's/-/_/g'}";
-	echo -e "\tport: ${_arg_port | sed 's/-/_/g'}";
-	echo -e "\tboard: ${_arg_board | sed 's/-/_/g'}";
-	echo -e "\tpio: ${_arg_pio | sed 's/-/_/g'}";
-	echo -e "\tota: ${_arg_ota | sed 's/-/_/g'}";
-	echo -e "\tfs: ${_arg_fs | sed 's/-/_/g'}";
+	echo -e "\tip: ${_arg_ip}";
+	echo -e "\tport: ${_arg_port}";
+	echo -e "\tboard: ${_arg_board}";
+	echo -e "\tpio: ${_arg_pio}";
+	echo -e "\tota: ${_arg_ota}";
+	echo -e "\tfs: ${_arg_fs}";
 
 }
 
-parse_commandline "$@"
-handle_passed_args_count
-assign_positional_args 1 "${_positionals[@]}"
+print_version()
+{
+	echo "";
+}
+
+on_interrupt() {
+	die Process aborted! 130;
+}
+
+parse_commandline "$@";
+handle_passed_args_count;
+assign_positional_args 1 "${_positionals[@]}";
+trap on_interrupt INT;
+
+
 
 # @parseArger-parsing-end
 # print_debug "$@"
